# .scrutinizer.yml
imports:
    - php
filter:
    excluded_paths:
        - 'tests/*'
tools:
    external_code_coverage:
        timeout: 900    # Timeout in seconds.
        runs: 4         # Scrutinizer will wait for n code coverage submissions
